import 'package:gg/model.dart';

class Autogenerated {
  String? message;
  Data? data;

  Autogenerated({this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  List<mList>? list;
  int? totalCount;

  Data({this.list, this.totalCount});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['list'] != null) {
      list = <mList>[];
      json['list'].forEach((v) {
        list!.add(new mList.fromJson(v));
      });
    }
    totalCount = json['totalCount'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.list != null) {
      data['list'] = this.list!.map((v) => v.toJson()).toList();
    }
    data['totalCount'] = this.totalCount;
    return data;
  }
}

class mList {
  String? sId;
  String? sName;
  String? sGlobalGalleryCategoryId;
  int? iDocType;
  int? iUid;
  int? iType;
  String? sUrl;
  String? sCreatedUserId;
  int? iCreatedAt;
  Null? nUpdatedUserId;
  int? iUpdatedAt;
  int? iStatus;
  int? iV;

  mList(
      {this.sId,
      this.sName,
      this.sGlobalGalleryCategoryId,
      this.iDocType,
      this.iUid,
      this.iType,
      this.sUrl,
      this.sCreatedUserId,
      this.iCreatedAt,
      this.nUpdatedUserId,
      this.iUpdatedAt,
      this.iStatus,
      this.iV});

  mList.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    sName = json['_name'];
    sGlobalGalleryCategoryId = json['_globalGalleryCategoryId'];
    iDocType = json['_docType'];
    iUid = json['_uid'];
    iType = json['_type'];
    sUrl = json['_url'];
    sCreatedUserId = json['_createdUserId'];
    iCreatedAt = json['_createdAt'];
    nUpdatedUserId = json['_updatedUserId'];
    iUpdatedAt = json['_updatedAt'];
    iStatus = json['_status'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['_name'] = this.sName;
    data['_globalGalleryCategoryId'] = this.sGlobalGalleryCategoryId;
    data['_docType'] = this.iDocType;
    data['_uid'] = this.iUid;
    data['_type'] = this.iType;
    data['_url'] = this.sUrl;
    data['_createdUserId'] = this.sCreatedUserId;
    data['_createdAt'] = this.iCreatedAt;
    data['_updatedUserId'] = this.nUpdatedUserId;
    data['_updatedAt'] = this.iUpdatedAt;
    data['_status'] = this.iStatus;
    data['__v'] = this.iV;
    return data;
  }
}
